# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/literate-copilot',
                'doc_host': 'https://fgiasson.github.io',
                'git_url': 'https://github.com/fgiasson/literate-copilot',
                'lib_path': 'literate_copilot'},
  'syms': { 'literate_copilot.main': { 'literate_copilot.main.abs': ('main.html#abs', 'literate_copilot/main.py'),
                                       'literate_copilot.main.add': ('main.html#add', 'literate_copilot/main.py'),
                                       'literate_copilot.main.divide': ('main.html#divide', 'literate_copilot/main.py'),
                                       'literate_copilot.main.factorial': ('main.html#factorial', 'literate_copilot/main.py'),
                                       'literate_copilot.main.log': ('main.html#log', 'literate_copilot/main.py'),
                                       'literate_copilot.main.mod': ('main.html#mod', 'literate_copilot/main.py'),
                                       'literate_copilot.main.multiply': ('main.html#multiply', 'literate_copilot/main.py'),
                                       'literate_copilot.main.power': ('main.html#power', 'literate_copilot/main.py'),
                                       'literate_copilot.main.root': ('main.html#root', 'literate_copilot/main.py'),
                                       'literate_copilot.main.sin': ('main.html#sin', 'literate_copilot/main.py'),
                                       'literate_copilot.main.subtract': ('main.html#subtract', 'literate_copilot/main.py'),
                                       'literate_copilot.main.version': ('main.html#version', 'literate_copilot/main.py')}}}
