# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_main.ipynb.

# %% auto 0
__all__ = ['app', 'version', 'add', 'subtract', 'multiply', 'divide', 'power', 'root', 'log', 'factorial', 'mod', 'abs', 'sin']

# %% ../nbs/00_main.ipynb 4
import numpy as np
import typer

# %% ../nbs/00_main.ipynb 6
app = typer.Typer()

# %% ../nbs/00_main.ipynb 8
@app.command()
def version():
    """Show version"""
    typer.echo("0.1.0")

# %% ../nbs/00_main.ipynb 10
@app.command()
def add(a: int = 1, b: int = 2):
    """Add two numbers"""
    typer.echo(a + b)

# %% ../nbs/00_main.ipynb 12
@app.command()
def subtract(a: int = 1, b: int = 2):
    """Subtract two numbers"""
    typer.echo(a - b)

# %% ../nbs/00_main.ipynb 14
@app.command()
def multiply(a: int = 1, b: int = 2):
    """Multiply two numbers"""
    typer.echo(a * b)

# %% ../nbs/00_main.ipynb 16
@app.command()
def divide(a: int = 1, b: int = 2):
    """Divide two numbers"""
    typer.echo(a / b)

# %% ../nbs/00_main.ipynb 18
@app.command()
def power(a: int = 1, b: int = 2):
    """Raise a number to the power of another"""
    typer.echo(a ** b)

# %% ../nbs/00_main.ipynb 20
@app.command()
def root(a: int = 1, b: int = 2):
    """Root a number by another"""
    typer.echo(a ** (1 / b))

# %% ../nbs/00_main.ipynb 22
@app.command()
def log(a: int = 1, b: int = 2):
    """Log a number by another"""
    typer.echo(np.log(a) / np.log(b))

# %% ../nbs/00_main.ipynb 24
@app.command()
def factorial(a: int = 1):
    """Factorial of a number"""
    typer.echo(np.math.factorial(a))

# %% ../nbs/00_main.ipynb 26
@app.command()
def mod(a: int = 1, b: int = 2):
    """Modulus of a number by another"""
    typer.echo(a % b)

# %% ../nbs/00_main.ipynb 28
@app.command()
def abs(a: int = 1):
    """Absolute value of a number"""
    typer.echo(np.abs(a))

# %% ../nbs/00_main.ipynb 30
@app.command()
def sin(a: int = 1):
    """Sin of a number"""
    typer.echo(np.sin(a))
